#pragma once

#include <SDL3/SDL_rect.h>

#define DUNGEON_SPRITE_COUNT 177

struct DungeonSpriteEntry {
    const SDL_FRect* frames;
    int frame_count;
    int pivot_x;
    int pivot_y;
};

extern const DungeonSpriteEntry DUNGEON_SPRITE_TABLE[DUNGEON_SPRITE_COUNT];

#define DUNGEON_SPRITE_LIST(X) \
    X(big_demon_idle) \
    X(big_demon_run) \
    X(big_zombie_idle) \
    X(big_zombie_run) \
    X(bomb) \
    X(chest_empty_open) \
    X(chest_full_open) \
    X(chest_mimic_open) \
    X(coin) \
    X(flask_big_blue) \
    X(flask_big_red) \
    X(flask_big_green) \
    X(flask_big_yellow) \
    X(flask_blue) \
    X(flask_red) \
    X(flask_green) \
    X(flask_yellow) \
    X(wizzard_f_hit) \
    X(wizzard_f_idle) \
    X(wizzard_f_run) \
    X(wizzard_m_hit) \
    X(wizzard_m_idle) \
    X(wizzard_m_run) \
    X(dwarf_m_idle) \
    X(imp_idle) \
    X(imp_run) \
    X(lizard_f_hit) \
    X(lizard_f_idle) \
    X(lizard_f_run) \
    X(dwarf_m_run) \
    X(dwarf_m_hit) \
    X(knight_f_hit) \
    X(knight_f_idle) \
    X(knight_f_run) \
    X(dwarf_f_idle) \
    X(dwarf_f_run) \
    X(dwarf_f_hit) \
    X(weapon_anime_sword) \
    X(weapon_arrow) \
    X(weapon_baton_with_spikes) \
    X(weapon_big_hammer) \
    X(weapon_bow) \
    X(weapon_bow_2) \
    X(weapon_double_axe) \
    X(weapon_cleaver) \
    X(weapon_duel_sword) \
    X(weapon_golden_sword) \
    X(weapon_green_magic_staff) \
    X(weapon_hammer) \
    X(weapon_katana) \
    X(weapon_knife) \
    X(weapon_knight_sword) \
    X(weapon_lavish_sword) \
    X(weapon_mace) \
    X(weapon_saw_sword) \
    X(weapon_machete) \
    X(weapon_red_gem_sword) \
    X(weapon_red_magic_staff) \
    X(weapon_regular_sword) \
    X(weapon_rusty_sword) \
    X(weapon_spear) \
    X(weapon_waraxe) \
    X(weapon_throwing_axe) \
    X(weapon_axe) \
    X(wogol_idle) \
    X(wogol_run) \
    X(zombie) \
    X(tiny_zombie_idle) \
    X(tiny_zombie_run) \
    X(goblin_idle) \
    X(goblin_run) \
    X(ice_zombie) \
    X(knight_m_idle) \
    X(knight_m_run) \
    X(knight_m_hit) \
    X(crate) \
    X(edge_down) \
    X(orc_shaman_idle) \
    X(orc_shaman_run) \
    X(swampy) \
    X(muddy) \
    X(necromancer) \
    X(masked_orc_idle) \
    X(masked_orc_run) \
    X(orc_warrior_idle) \
    X(orc_warrior_run) \
    X(skelet_idle) \
    X(skelet_run) \
    X(skull) \
    X(ogre_idle) \
    X(ogre_run) \
    X(ui_heart_empty) \
    X(ui_heart_full) \
    X(ui_heart_half) \
    X(doc_idle) \
    X(doc_run) \
    X(pumpkin_dude_idle) \
    X(pumpkin_dude_run) \
    X(angel_idle) \
    X(angel_run) \
    X(chort_idle) \
    X(chort_run) \
    X(column) \
    X(column_wall) \
    X(wall_fountain_mid_blue) \
    X(wall_fountain_mid_red) \
    X(wall_fountain_basin_red) \
    X(wall_fountain_basin_blue) \
    X(wall_goo_base) \
    X(wall_goo) \
    X(wall_hole_1) \
    X(wall_hole_2) \
    X(wall_banner_blue) \
    X(wall_banner_red) \
    X(wall_banner_green) \
    X(wall_banner_yellow) \
    X(floor_ladder) \
    X(floor_spikes) \
    X(hole) \
    X(floor_stairs) \
    X(floor_1) \
    X(floor_2) \
    X(floor_3) \
    X(floor_4) \
    X(floor_5) \
    X(floor_6) \
    X(floor_7) \
    X(floor_8) \
    X(wall_left) \
    X(wall_mid) \
    X(wall_right) \
    X(wall_top_left) \
    X(wall_top_mid) \
    X(wall_top_right) \
    X(lizard_m_idle) \
    X(lizard_m_run) \
    X(lizard_m_hit) \
    X(elf_f_idle) \
    X(elf_f_run) \
    X(elf_f_hit) \
    X(elf_m_idle) \
    X(elf_m_run) \
    X(elf_m_hit) \
    X(button_red_up) \
    X(button_red_down) \
    X(button_blue_up) \
    X(button_blue_down) \
    X(lever_left) \
    X(lever_right) \
    X(doors_frame_left) \
    X(doors_frame_right) \
    X(doors_frame_top) \
    X(doors_leaf_closed) \
    X(doors_leaf_open) \
    X(wall_edge_bottom_left) \
    X(wall_edge_bottom_right) \
    X(wall_edge_mid_left) \
    X(wall_edge_top_left) \
    X(wall_edge_left) \
    X(wall_edge_top_right) \
    X(wall_edge_right) \
    X(wall_edge_mid_right) \
    X(wall_edge_tshape_bottom_right) \
    X(wall_edge_tshape_bottom_left) \
    X(wall_edge_tshape_right) \
    X(wall_edge_tshape_left) \
    X(wall_outer_front_right) \
    X(wall_outer_front_left) \
    X(wall_outer_mid_left) \
    X(wall_outer_top_left) \
    X(wall_outer_top_right) \
    X(wall_outer_mid_right) \
    X(wall_fountain_top_1) \
    X(wall_fountain_top_2) \
    X(wall_fountain_top_3) \
    X(slug) \
    X(tiny_slug)
